### ISSUE TITLE
Request: automatic hiding and unhiding of minor columns

### ISSUE THREAD

**Issue by mjtsuk** [etowle/1822#43]
It would be nice if only the active minor columns were visible in the spreadsheet: it would save a lot of scrolling. I think only the minors that have been in the bidding boxes should be visible. If you like, I could work on how to do it in the scripts.

**Comment by etowle** [comment]
That's a good idea. Sure, feel free to work on this. The hidden columns CQ and CR (in the 1822CA sheet) are used to conditionally format the minor draw pile list, based on if a minor is currently in a bid box or was previously auctioned off. Maybe you can use these TRUE/FALSE values to easily determine which minors should be visible. But this includes minors from bid box 1 that were exported at the end of an SR, which don't necessarily need to be visible.

Is it best to leave all minors visible in the SR1 sheet? Otherwise, the minor columns would have to be updated whenever the seed is changed in Setup. That could be messy.

**Comment by etowle** [comment]
You could also loop through the minor columns and display each column only if any of the column data is nonempty (director, operational data, merger comments, etc.).
